(ns simple-editor.widgets.text.run
  (:require 
   ["dart:ui" :as ui]))

;; line layout
(defn paragraph [spans]
  (->> spans
      ;;  parchment
    ;;    line-breaks
    ;;    layout 
    ;;    paint
       ))

(defn layout []
  ;; layout
  ;; layout widgetspan
  ;; layout paragraph
    ;; layout line
  nil)

(defn draw []
  ;; draw-widget-span
  ;; draw-paragraph
  ;; draw-line
  ;; draw-text-run
  nil)

(defn draw []
  ;; draw-selection-range
  nil
  )